### ISSUE TITLE
Remove Instagram

### ISSUE THREAD

**Issue by RebelCoderJames** [bettercallmilan/bettercallmilan.github.io#2]

**Comment by bettercallmilan** [comment]
bad issue. instagram is very important

**Comment by RebelCoderJames** [comment]
for what? selling peoples data

**Comment by bettercallmilan** [comment]
yes

**Comment by RebelCoderJames** [comment]
ah ok. why not use facebook tracking? https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fbusiness%2Ftools%2Fmeta-pixel%2F

**Comment by RebelCoderJames** [comment]
rethink it. i cant open youre website if its traking me

**Comment by bettercallmilan** [comment]
your*

**Comment by bettercallmilan** [comment]
tracking*
